### ISSUE TITLE
SexlabUtil.dll and PapyrusUtil.dll disabled, incompatible with current runtime version

### ISSUE THREAD

**Issue by ahoffskov** [eeveelo/SexLab#31]
![skse-error](https://user-images.githubusercontent.com/36532723/144415421-dbfdcce3-45b3-4738-8ac5-ae01ea336079.png)

SKSE v. 2.1.3
SkyrimSE.exe v. 1.6.323

**Comment by eeveelo** [comment]
you're using the wrong version of the mod. you need to be using 1.64b.
