### ISSUE TITLE
CleanActorStorage:  Starting...   CTD

### ISSUE THREAD

**Issue by GuruSR** [eeveelo/SexLab#36]
I have one save game that is causing this.  I checked, all the patches (SKSE64), etc are up to date.  Using 1.65 with skse 2.2.3 and runtime 1.6.640.  The other saves don't have this issue, so something it has, is causing it to crash.

**Comment by GuruSR** [comment]
`[11/25/2022 - 12:22:33AM] SEXLAB - NOTICE: SexLabFramework - Enabled`
`[11/25/2022 - 12:22:33AM] SexLab  - SexLab Update v1.65 AE - Ready!`
`[11/25/2022 - 12:22:33AM] SEXLAB - CleanActorStorage: Starting...`
`[11/25/2022 - 12:22:37AM] SEXLAB - CleanActorStorage: 52 -> 46`

**Comment by osmelmc** [comment]
Try installing the "SexLab Utility Plus" and disabling the DebugMode on the SexLab MCM before reach that part.

The last version of "SexLab Utility Plus" have a experimental fix that should allow you disable the DebugMode even while is in middle of the update process and should scape the scripts that cause the CTD.

**Comment by GuruSR** [comment]
Can you give me a link to the valid download so I know which one I'm aiming to install to avoid anything "fishy".

**Comment by osmelmc** [comment]
https://www.loverslab.com/files/file/10316-osmelmc-mod-tweaks/

**Comment by GuruSR** [comment]
Okay, doing some testing, after installing SUP, I didn't do the Sexlab Debug Mode Disable (it is disabled) OR the Sexlab Clean System, it actually went through the CleanActorStorage, but as soon as I did the Sexlab Clean System, it CTD'd in the same spot, so now what would you suggest?

**Comment by GuruSR** [comment]
```
[12/05/2022 - 11:48:41AM] SEXLAB - NOTICE Custom5 - Failed to import ../SexLab/Expression_Custom5.json
[12/05/2022 - 11:48:41AM] SEXLAB - NOTICE Custom4 - Failed to import ../SexLab/Expression_Custom4.json
[12/05/2022 - 11:48:41AM] SEXLAB - NOTICE Custom3 - Failed to import ../SexLab/Expression_Custom3.json
[12/05/2022 - 11:48:41AM] SEXLAB - NOTICE Custom2 - Failed to import ../SexLab/Expression_Custom2.json
[12/05/2022 - 11:48:41AM] SEXLAB - NOTICE Custom1 - Failed to import ../SexLab/Expression_Custom1.json
[12/05/2022 - 11:48:43AM] Error: Static function ResetPhonemeModifier not found on object mfgconsolefunc. Aborting call and returning None
stack:
	[SexLabQuestFramework (08000D62)].sslSystemConfig.reload() - "sslSystemConfig.psc" Line 1169
	[SexLabQuestFramework (08000D62)].sslSystemConfig.ImportSettings() - "sslSystemConfig.psc" Line 2651
	[alias playerAlias on quest SexLabQuestFramework (08000D62)].sslsystemalias.UpdateSystem() - "sslSystemAlias.psc" Line 173
	[alias playerAlias on quest SexLabQuestFramework (08000D62)].sslsystemalias.OnPlayerLoadGame() - "sslSystemAlias.psc" Line 38
[12/05/2022 - 11:48:43AM] WARNING: Assigning None to a non-object variable named "::temp244"
stack:
	[SexLabQuestFramework (08000D62)].sslSystemConfig.reload() - "sslSystemConfig.psc" Line 1169
	[SexLabQuestFramework (08000D62)].sslSystemConfig.ImportSettings() - "sslSystemConfig.psc" Line 2651
	[alias playerAlias on quest SexLabQuestFramework (08000D62)].sslsystemalias.UpdateSystem() - "sslSystemAlias.psc" Line 173
	[alias playerAlias on quest SexLabQuestFramework (08000D62)].sslsystemalias.OnPlayerLoadGame() - "sslSystemAlias.psc" Line 38
[12/05/2022 - 11:48:43AM] SEXLAB - GetFurnitureType(None): Invalid form or Furniture List's Empty.
[12/05/2022 - 11:48:43AM] SEXLAB - NOTICE: Updating furnitures for mod 'HearthFires.esm'
[12/05/2022 - 11:48:45AM] SEXLAB - NOTICE: SexLabFramework - Enabled
[12/05/2022 - 11:48:45AM] SexLab  - SexLab Update v1.65 AE - Ready!
[12/05/2022 - 11:48:45AM] SEXLAB - CleanActorStorage: Starting...
[12/05/2022 - 11:48:54AM] SEXLAB - CleanActorStorage: Done - 113
```

Shortly after that, CTD, thinking something else is causing this after an update, the errors with the sslSystemAlias might be to blame.

**Comment by osmelmc** [comment]
The DebugMode isn't disabled if you can see the "SEXLAB -  " on the Papyrus.0.log or the console.

Check that is still disabled at that point

**Comment by GuruSR** [comment]
But Sexlab is updating and the menus are dead, how does one turn that off during Sexlab updating to 1.65?

**Comment by osmelmc** [comment]
I only test it after use the clean system, so i will check.

**Comment by osmelmc** [comment]
This CTD don't happen for everyone and is related with the PapyrusUtil. If you are using Skyrim SE probably you have the official version overwriting the one that comes with the SexLab Framework. Both have the same version number but are very different.

**Comment by eeveelo** [comment]
Your crash has nothing to do with CleanActorStorage. The fact that your log shows the line ```CleanActorStorage: Done - 113``` means it completed running the function without issue. If it were causing a crash, your game would be crashing after the ```CleanActorStorage: Starting...``` line before the done line is logged.

You probably just need to do a clean install. Remove sexlab and it's related mods, make a clean save without it installed, then quit and re-install sexlab framework by itself without any additional sexlab mods, make another save once sexlab is finished it's install process in-game, quit and re-install your other sexlab mods a few at a time.

>Both have the same version number but are very different.

The official version and the version packaged with sexlab are 100% identical and always will be. When I update papyrusutil's version, I update sexlab as well to make sure it's packaged with the newest version.

**Comment by osmelmc** [comment]
The version of PapyrusUtil I'm using have more functions on the PapyrusUtil.psc that those on the download page's (Nexus, LoversLab) so looks more like the AE version but is for SE and keep showing the version number 39.

I didn't notice that until did one mod with those functions and some SSE users send me logs reporting those functions missing so i download the Nexus version to compare and was true.

I can't compile DLL files so the only explication is that was the version on this repository when the last version of SexLab for SE was released. By the way I'm still playing on SE and I know the CTD just before the end of the CleanActorStorage because even I had a few of those before update to the last SexLab v1.63.

All the crash logs shared by the users about that CTD point to one PapyrusUtil debug function that is called after the end of the CleanActorStorage so the CleanActorStorage is fine but is everyone reference so I'm not longer make efforts on point it.

**Comment by GuruSR** [comment]
I manually update mods, so any SKSE plugins, I just tell it to overwrite all, Sexlab was the last one I updated because I needed the plugin from it.  This is Skyrim AE, I did have 1 save game that CTD'd before the Done message, this other save did CTD after, I commented out the debug_Cleanup() in sslSystemAlias's function CleanActorStorage().

So for clarity, which PapyrusUtil should be used, the one IN Sexlab 1.65?  If so, it should be there.

**Comment by eeveelo** [comment]
@osmelmc You probably downgraded the dll for 1.5.97 but not the scripts. The versions included with sexlab have always been identical to the papyrusutil released for it's game version.

@GuruSR I highly doubt your crash has anything to do with papyrusutil or debug mode. Just clean your save file and do clean installs of the mods until you narrow down the cause of the crash. The last line in your debug log is not a great indicator of cause when it comes to hard crashes.

The debug log shows what the game did without crashing, not what it crashed trying to do.
